create table if not exists public.exercises (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  equipment text[] not null default '{}'::text[],
  muscle_groups text[] not null default '{}'::text[],
  instructions text,
  is_active boolean not null default true
);

alter table public.exercises enable row level security;

grant select on public.exercises to authenticated;

drop policy if exists "exercises_select_active" on public.exercises;
create policy "exercises_select_active"
on public.exercises
for select
to authenticated
using (is_active = true);

create table if not exists public.user_workouts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text,
  is_template boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists user_workouts_user_id_updated_at_idx on public.user_workouts (user_id, updated_at desc);

alter table public.user_workouts enable row level security;

grant select, insert, update, delete on public.user_workouts to authenticated;

drop policy if exists "user_workouts_select_own" on public.user_workouts;
create policy "user_workouts_select_own"
on public.user_workouts
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "user_workouts_insert_own" on public.user_workouts;
create policy "user_workouts_insert_own"
on public.user_workouts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "user_workouts_update_own" on public.user_workouts;
create policy "user_workouts_update_own"
on public.user_workouts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_workouts_delete_own" on public.user_workouts;
create policy "user_workouts_delete_own"
on public.user_workouts
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.workout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  user_workout_id uuid references public.user_workouts(id) on delete set null,
  source_type text not null check (source_type in ('user_workout', 'premium_workout', 'quick_log')),
  source_id text,
  status text not null default 'completed' check (status in ('started', 'completed', 'abandoned')),
  started_at timestamptz not null,
  completed_at timestamptz,
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  rpe integer check (rpe is null or (rpe >= 1 and rpe <= 10)),
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists workout_sessions_user_id_started_at_idx on public.workout_sessions (user_id, started_at desc);

alter table public.workout_sessions enable row level security;

grant select, insert, update, delete on public.workout_sessions to authenticated;

drop policy if exists "workout_sessions_select_own" on public.workout_sessions;
create policy "workout_sessions_select_own"
on public.workout_sessions
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "workout_sessions_insert_own" on public.workout_sessions;
create policy "workout_sessions_insert_own"
on public.workout_sessions
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "workout_sessions_update_own" on public.workout_sessions;
create policy "workout_sessions_update_own"
on public.workout_sessions
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "workout_sessions_delete_own" on public.workout_sessions;
create policy "workout_sessions_delete_own"
on public.workout_sessions
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.premium_workouts (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text,
  level text not null default 'beginner' check (level in ('beginner', 'intermediate', 'advanced')),
  est_duration_minutes integer,
  is_published boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.premium_workouts enable row level security;

grant select on public.premium_workouts to authenticated;

drop policy if exists "premium_workouts_select_published" on public.premium_workouts;
create policy "premium_workouts_select_published"
on public.premium_workouts
for select
to authenticated
using (is_published = true);

create table if not exists public.premium_plans (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  description text,
  level text not null default 'beginner' check (level in ('beginner', 'intermediate', 'advanced')),
  weeks integer not null default 4 check (weeks > 0),
  is_published boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.premium_plans enable row level security;

grant select on public.premium_plans to authenticated;

drop policy if exists "premium_plans_select_published" on public.premium_plans;
create policy "premium_plans_select_published"
on public.premium_plans
for select
to authenticated
using (is_published = true);

create table if not exists public.premium_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  entitlement_id text not null default 'premium',
  is_active boolean not null default false,
  expires_at timestamptz,
  source text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

alter table public.premium_entitlements enable row level security;

grant select on public.premium_entitlements to authenticated;

drop policy if exists "premium_entitlements_select_own" on public.premium_entitlements;
create policy "premium_entitlements_select_own"
on public.premium_entitlements
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.handle_user_workouts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_user_workouts_updated_at on public.user_workouts;
create trigger set_user_workouts_updated_at
before update on public.user_workouts
for each row
execute function public.handle_user_workouts_updated_at();

create or replace function public.handle_workout_sessions_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_workout_sessions_updated_at on public.workout_sessions;
create trigger set_workout_sessions_updated_at
before update on public.workout_sessions
for each row
execute function public.handle_workout_sessions_updated_at();

create or replace function public.handle_premium_workouts_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_premium_workouts_updated_at on public.premium_workouts;
create trigger set_premium_workouts_updated_at
before update on public.premium_workouts
for each row
execute function public.handle_premium_workouts_updated_at();

create or replace function public.handle_premium_plans_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_premium_plans_updated_at on public.premium_plans;
create trigger set_premium_plans_updated_at
before update on public.premium_plans
for each row
execute function public.handle_premium_plans_updated_at();

create or replace function public.handle_premium_entitlements_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_premium_entitlements_updated_at on public.premium_entitlements;
create trigger set_premium_entitlements_updated_at
before update on public.premium_entitlements
for each row
execute function public.handle_premium_entitlements_updated_at();
